"""SQLite-backed review queue for pending SBAR alert drafts.

Stores Communication drafts generated by generate_escalation_note (via the
A2A agent) that are awaiting clinician approval. The queue survives page
reloads because it lives on disk (not in process memory).

The approve endpoint (POST /api/patients/{id}/alerts/{alertId}/approve) reads
from here, writes Communication + AuditEvent to HAPI, then marks the row
'completed'. No other path mutates this table.

Security note (SEC-16): SQLite file is unencrypted on disk. All data is
synthetic — not real PHI. Production deployment would use SQLCipher or a
managed database with encryption at rest.
"""

from __future__ import annotations

import contextlib
import json
import sqlite3
import uuid
from collections.abc import Generator
from contextlib import contextmanager
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

# Store the DB next to this file so it's always in the backend/api/ directory.
DB_PATH = Path(__file__).parent / "review_queue.db"


@contextmanager
def _conn() -> Generator[sqlite3.Connection, None, None]:
    con = sqlite3.connect(str(DB_PATH), check_same_thread=False)
    con.row_factory = sqlite3.Row
    try:
        yield con
        con.commit()
    finally:
        con.close()


# ---------------------------------------------------------------------------
# Schema
# ---------------------------------------------------------------------------


def init_db() -> None:
    """Create tables and indexes if they don't exist. Call once at startup."""
    with _conn() as con:
        con.execute("""
            CREATE TABLE IF NOT EXISTS alerts (
                id                      TEXT PRIMARY KEY,
                patient_id              TEXT NOT NULL,
                severity                TEXT NOT NULL,
                sbar_json               TEXT NOT NULL,
                narrative               TEXT NOT NULL,
                recipient_role          TEXT NOT NULL,
                model_used              TEXT NOT NULL,
                communication_draft_json TEXT NOT NULL,
                status                  TEXT NOT NULL DEFAULT 'in-progress',
                created_at              TEXT NOT NULL,
                updated_at              TEXT,
                acknowledged_at         TEXT,
                clinician_id            TEXT,
                note                    TEXT,
                audit_id                TEXT
            )
        """)
        # column may already exist in an older DB
        with contextlib.suppress(sqlite3.OperationalError):
            con.execute("ALTER TABLE alerts ADD COLUMN updated_at TEXT")
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_alerts_patient ON alerts(patient_id)"
        )
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts(status)"
        )
        con.execute(
            "CREATE INDEX IF NOT EXISTS idx_alerts_created ON alerts(created_at DESC)"
        )


# ---------------------------------------------------------------------------
# Write operations
# ---------------------------------------------------------------------------


def enqueue_alert(
    patient_id: str,
    severity: str,
    sbar: dict[str, Any],
    narrative: str,
    recipient_role: str,
    model_used: str,
    communication_draft: dict[str, Any],
) -> str:
    """Insert a new in-progress alert. Returns the generated alert id."""
    alert_id = f"alert-{uuid.uuid4().hex[:8]}"
    now = datetime.now(UTC).isoformat()
    with _conn() as con:
        con.execute(
            """
            INSERT INTO alerts
              (id, patient_id, severity, sbar_json, narrative,
               recipient_role, model_used, communication_draft_json,
               status, created_at)
            VALUES (?, ?, ?, ?, ?, ?, ?, ?, 'in-progress', ?)
            """,
            (
                alert_id,
                patient_id,
                severity,
                json.dumps(sbar),
                narrative,
                recipient_role,
                model_used,
                json.dumps(communication_draft),
                now,
            ),
        )
    return alert_id


def claim_alert_for_writing(alert_id: str) -> dict[str, Any] | None:
    """Atomically transition status 'in-progress' → 'in-progress-writing'.

    Returns the claimed row if this thread won the race; returns None if the
    alert is not found, already completed, or another thread already claimed it
    (caller should return 409 Conflict).

    SQLite's row-level locking ensures only one UPDATE wins when two threads
    race on the same alert_id.
    """
    now = datetime.now(UTC).isoformat()
    with _conn() as con:
        cursor = con.execute(
            """
            UPDATE alerts
            SET status = 'in-progress-writing', updated_at = ?
            WHERE id = ? AND status = 'in-progress'
            RETURNING *
            """,
            (now, alert_id),
        )
        row = cursor.fetchone()
    return _row_to_dict(row) if row else None


def revert_alert_to_in_progress(alert_id: str) -> None:
    """Revert 'in-progress-writing' → 'in-progress' after a HAPI write failure.

    Allows the next approve attempt to retry rather than leaving the alert
    permanently locked.
    """
    now = datetime.now(UTC).isoformat()
    with _conn() as con:
        con.execute(
            "UPDATE alerts SET status = 'in-progress', updated_at = ? WHERE id = ?",
            (now, alert_id),
        )


def approve_alert(
    alert_id: str,
    clinician_id: str,
    note: str,
    audit_id: str,
) -> dict[str, Any] | None:
    """Mark an alert completed and record clinician acknowledgement.

    Returns the updated row dict, or None if alert_id is not found.
    """
    now = datetime.now(UTC).isoformat()
    with _conn() as con:
        con.execute(
            """
            UPDATE alerts
            SET status = 'completed',
                acknowledged_at = ?,
                clinician_id = ?,
                note = ?,
                audit_id = ?,
                updated_at = ?
            WHERE id = ?
            """,
            (now, clinician_id, note, audit_id, now, alert_id),
        )
    return get_alert(alert_id)


# ---------------------------------------------------------------------------
# Read operations
# ---------------------------------------------------------------------------


def get_alert(alert_id: str) -> dict[str, Any] | None:
    """Return a single alert row as dict, or None if not found."""
    with _conn() as con:
        row = con.execute(
            "SELECT * FROM alerts WHERE id = ?", (alert_id,)
        ).fetchone()
    return _row_to_dict(row) if row else None


def get_latest_alert(patient_id: str) -> dict[str, Any] | None:
    """Return the most recently created alert for a patient (any status)."""
    with _conn() as con:
        row = con.execute(
            """
            SELECT * FROM alerts
            WHERE patient_id = ?
            ORDER BY created_at DESC
            LIMIT 1
            """,
            (patient_id,),
        ).fetchone()
    return _row_to_dict(row) if row else None


def list_pending_alerts() -> list[dict[str, Any]]:
    """Return all in-progress alerts ordered by severity then creation time."""
    with _conn() as con:
        rows = con.execute(
            """
            SELECT * FROM alerts
            WHERE status = 'in-progress'
            ORDER BY
              CASE severity
                WHEN 'critical' THEN 0
                WHEN 'urgent'   THEN 1
                ELSE 2
              END,
              created_at DESC
            """
        ).fetchall()
    return [_row_to_dict(r) for r in rows]


def count_unread_alerts(patient_id: str) -> int:
    """Count in-progress alerts for a patient."""
    with _conn() as con:
        row = con.execute(
            """
            SELECT COUNT(*) FROM alerts
            WHERE patient_id = ? AND status = 'in-progress'
            """,
            (patient_id,),
        ).fetchone()
    return int(row[0]) if row else 0


def get_latest_alert_at(patient_id: str) -> str | None:
    """Return created_at of the most recent alert for a patient, or None."""
    with _conn() as con:
        row = con.execute(
            """
            SELECT created_at FROM alerts
            WHERE patient_id = ?
            ORDER BY created_at DESC
            LIMIT 1
            """,
            (patient_id,),
        ).fetchone()
    return str(row[0]) if row else None


# ---------------------------------------------------------------------------
# Internal helper
# ---------------------------------------------------------------------------


def _row_to_dict(row: sqlite3.Row) -> dict[str, Any]:
    d: dict[str, Any] = dict(row)
    d["sbar"] = json.loads(d.pop("sbar_json"))
    d["communication_draft"] = json.loads(d.pop("communication_draft_json"))
    return d


# Ensure table exists on import — CREATE TABLE IF NOT EXISTS is idempotent.
init_db()
