#!/usr/bin/env bash
#
# Vigil — AWS EC2 cloud-init bootstrap
#
# Paste this into the "User data" field when launching a c7i-flex.large
# Ubuntu 22.04 instance. It runs once on first boot and:
#
#   1. Installs Docker + docker-compose (v2 plugin)
#   2. Clones the Vigil repo to /opt/vigil
#   3. Generates a fresh VIGIL_API_KEY and writes .env
#   4. Brings up the full stack with `docker compose up -d`
#   5. Prints URLs + credentials to the cloud-init log
#
# After launch, SSH in and:
#   tail -f /var/log/cloud-init-output.log
#
# Credentials and the public URL appear at the bottom of that log.
#
# Two things you MUST customize before pasting (see variables below):
#   - SITE_DOMAIN  (your domain, or `<public-ip-with-dashes>.sslip.io`)
#   - LLM_PROVIDER + the matching API key  (GROQ_API_KEY or ANTHROPIC_API_KEY)
# ---------------------------------------------------------------------------

set -euxo pipefail

# ----------------------- Customization — edit these ------------------------
# Option (a) user-owned domain:      SITE_DOMAIN="vigil.example.com"
# Option (b) free sslip.io (default): leave SITE_DOMAIN="" and we'll auto-fill
#                                     <public-ip-dashes>.sslip.io on first boot
# Option (c) local HTTP testing:     SITE_DOMAIN=":80"
SITE_DOMAIN="${SITE_DOMAIN:-}"

# Pick one:  groq | claude | ollama | stub
LLM_PROVIDER="${LLM_PROVIDER:-groq}"

# Paste the matching key (leave the others empty)
GROQ_API_KEY="${GROQ_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"

# Vigil repo — public GitHub. Override if you fork.
VIGIL_REPO="${VIGIL_REPO:-https://github.com/raymondchrisandy/vigil.git}"
VIGIL_BRANCH="${VIGIL_BRANCH:-main}"
VIGIL_DIR="/opt/vigil"
# ---------------------------------------------------------------------------

echo "==> Vigil bootstrap starting at $(date -Is)"

# 1. Apt update + Docker install (official repo)
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y ca-certificates curl git openssl jq

install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg \
  -o /etc/apt/keyrings/docker.asc
chmod a+r /etc/apt/keyrings/docker.asc

echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] \
  https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" \
  > /etc/apt/sources.list.d/docker.list

apt-get update -y
apt-get install -y \
  docker-ce docker-ce-cli containerd.io \
  docker-buildx-plugin docker-compose-plugin

# 2. Add ubuntu user to docker group so `docker` works without sudo
usermod -aG docker ubuntu || true

# 3. Clone the repo
if [ ! -d "$VIGIL_DIR/.git" ]; then
  git clone --branch "$VIGIL_BRANCH" --depth 1 "$VIGIL_REPO" "$VIGIL_DIR"
else
  git -C "$VIGIL_DIR" pull --ff-only
fi
chown -R ubuntu:ubuntu "$VIGIL_DIR"

# 4. Auto-derive SITE_DOMAIN if blank — use sslip.io against public IPv4
if [ -z "$SITE_DOMAIN" ]; then
  # IMDSv2 — fetch token first, then metadata
  IMDS_TOKEN=$(curl -sS -X PUT "http://169.254.169.254/latest/api/token" \
    -H "X-aws-ec2-metadata-token-ttl-seconds: 60")
  PUBLIC_IP=$(curl -sS -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" \
    http://169.254.169.254/latest/meta-data/public-ipv4)
  if [ -n "$PUBLIC_IP" ]; then
    SITE_DOMAIN="${PUBLIC_IP//./-}.sslip.io"
    echo "==> Auto-derived SITE_DOMAIN=$SITE_DOMAIN (sslip.io)"
  else
    echo "==> WARNING: no public IP from IMDS; falling back to :80 (no TLS)"
    SITE_DOMAIN=":80"
  fi
fi

# 5. Generate a fresh API key and write .env
VIGIL_API_KEY=$(openssl rand -hex 32)

cat > "$VIGIL_DIR/.env" <<EOF
# Generated by deploy/aws/user-data.sh at $(date -Is)
# ---------------------------------------------------------------
VIGIL_API_KEY=$VIGIL_API_KEY
SITE_DOMAIN=$SITE_DOMAIN

LLM_PROVIDER=$LLM_PROVIDER
GROQ_API_KEY=$GROQ_API_KEY
ANTHROPIC_API_KEY=$ANTHROPIC_API_KEY

# CORS restricted to the site domain; loopback kept for ssh-tunnel debugging.
CORS_ORIGINS=https://$SITE_DOMAIN,http://localhost:3000

# A2A_PUBLIC_URL lands inside the AgentCard for external callers.
A2A_PUBLIC_URL=https://$SITE_DOMAIN
EOF
chown ubuntu:ubuntu "$VIGIL_DIR/.env"
chmod 600 "$VIGIL_DIR/.env"

# 6. Boot the stack
cd "$VIGIL_DIR"
docker compose pull || true
# Build the backend + frontend images (~3-5 min first time; Next.js build
# dominates the wall-clock).
docker compose build
docker compose up -d

# 7. Seed HAPI with synthetic patients (non-blocking, best-effort — HAPI
# may take ~60s to become healthy).
(
  for i in $(seq 1 30); do
    if curl -sf "http://127.0.0.1:8080/fhir/metadata" >/dev/null; then
      echo "==> HAPI is up; seeding patients"
      docker compose exec -T api \
        python data/seed_hapi.py \
          --fhir-base http://hapi:8080/fhir \
          --src data/patients || true
      break
    fi
    sleep 10
  done
) &

# 8. Summary for the cloud-init log
cat <<BANNER

==============================================================
 Vigil is starting. Give it ~2-3 minutes to settle (Next.js
 build + HAPI warm-up + first Let's Encrypt cert issuance).
==============================================================

 Site:           https://$SITE_DOMAIN
 AgentCard:      https://$SITE_DOMAIN/.well-known/agent-card.json
 API health:     https://$SITE_DOMAIN/api/health
 MCP endpoint:   https://$SITE_DOMAIN/mcp
 VIGIL_API_KEY:  $VIGIL_API_KEY

 Working dir:    $VIGIL_DIR
 Env file:       $VIGIL_DIR/.env   (chmod 600, ubuntu:ubuntu)

 Useful commands (SSH in as ubuntu@<ec2-ip>):
   cd /opt/vigil && docker compose ps
   docker compose logs -f caddy
   docker compose logs -f mcp a2a api frontend
   docker compose restart

==============================================================
BANNER

echo "==> Vigil bootstrap finished at $(date -Is)"
